### ISSUE TITLE
Query String Messages

### ISSUE THREAD

**Issue by TangoYankee** [TangoYankee/markdownlinks#28]
Current messages are generated from variables sent through query
   - message persists through refresh
   -  attacker may send erroneous messages through query

Consider refactoring to sessions-based messaging

**Comment by TangoYankee** [comment]
So long as none of the core application logic is affected by the query string, then it is fine to deliver error/success messages.

**Comment by Kenworthe** [comment]
If you are concerned about the text following the `?`persisting in the url, there might be some hacky things you can do to manipulate the `window` object without a page reload, after receiving the query text and rendering it to display.
